### ISSUE TITLE
Typo inside the README

### ISSUE THREAD

**Issue by gyuhyun-lee** [cmuratori/dtc#1]
Hi! Thank you for continuing handmade hero, it is the single best source to learn how to _actually_ programming for me.

Minor thing, but just wanted to inform you that there's a typo inside the README.

'Moving CreteWindow/DestroyWindow' ->I guess what you wanted to say was 'Moving CreateWindow/DestroyWindow'?

Again, thank you for your continuous effort for teaching, and hope you have a great day!

**Comment by cmuratori** [comment]
Roger that - should be fixed now.

\- Casey
