### ISSUE TITLE
[Question] Could we use Fibers to solve this problem?

### ISSUE THREAD

**Issue by g-berthiaume** [cmuratori/dtc#2]
Hi Casey,

Your post has reminded me of a [Handmade Bitwise's stream](https://youtu.be/NG_mUhc8LRw?t=3355) from [Per Vognsen](https://mobile.twitter.com/pervognsen). 

I remember him using a [Fiber](https://docs.microsoft.com/en-us/windows/win32/procthread/fibers) to solve this problem.
I'm a beginner in the Windows programming world, so I was wondering if you could comment on what are the tradeoffs between those 2 approaches.

Thanks for sharing your knowledge and enthusiasm about system programming.

Regards,
-Gabriel

**Comment by cmuratori** [comment]
You can use fibers to solve a subset of this problem, but it is difficult to solve the problem completely with fibers.

Fibers assume you have a single main loop, and the goal is to prevent that single main loop from blocking on Windows. This is a simplified version of the more general problem, which is that you may have lots of threads doing lots of things, and you don't want any of them to ever block on Windows' message loop.  It would be very difficult to solve _that_ problem with fibers, especially if you don't assume that any particular thread "owns" any particular window (eg., multiple threads may be doing things with multiple windows, etc.)

\- Casey

**Comment by g-berthiaume** [comment]
Interesting.
Thank you!

Cordialement,
-Gabriel
